"""Phase 12 MetaTrader 5 (MT5) Execution Adapter Domain Module."""

from acash.execution.mt5.adapter import MT5BrokerAdapter, MT5BrokerObservation
from acash.execution.mt5.enums import (
    MT5AccountMarginMode,
    MT5DealEntry,
    MT5DealType,
    MT5ExecutionPolicy,
    MT5FillingMode,
    MT5OrderState,
    MT5OrderTime,
    MT5OrderType,
    MT5PositionType,
    MT5Retcode,
    MT5TradeAction,
    MT5TradeExecutionMode,
    MT5ApiErrorCode,
)
from acash.execution.mt5.exceptions import (
    MT5DomainError,
    MT5FillingModeError,
    MT5NormalizationError,
    MT5ReconciliationError,
    MT5RetcodeError,
    MT5SymbolSpecError,
    MT5TransportError,
    MT5ValidationError,
    ReconciliationIntegrityError,
)
from acash.execution.mt5.reconciliation import (
    ACASHShadowLedger,
    ACASHShadowLedgerSnapshot,
    CaptureCompletenessStatus,
    DEAL_CATEGORY_MAP,
    HistoricalDealCoverage,
    HistoricalDealScopeKind,
    MT56DReconciliationReport,
    MT5BrokerRealitySnapshot,
    MT5DealCategory,
    MT5Discrepancy,
    MT5DiscrepancyKind,
    MT5DiscrepancySeverity,
    MT5ReconciliationEngine,
    ReconciliationCaptureContext,
    ReconciliationStatus,
    ReconciliationToleranceConfig,
    ShadowDealRecord,
    ShadowPosition,
    ShadowRestingOrder,
    canonical_json,
    categorize_deal,
    compute_payload_digest,
    match_position_identity,
    verify_order_deal_execution,
)
from acash.execution.mt5.mapping import (
    MQL5_DEAL_ENTRY_DECODE_MAP,
    MQL5_DEAL_TYPE_DECODE_MAP,
    MQL5_MARGIN_MODE_DECODE_MAP,
    REJECT_RETCODES,
    SUPPORTED_MT5_RETCODES,
    classify_trade_result_observation,
    decode_mt5_deal_entry,
    decode_mt5_deal_type,
    decode_mt5_margin_mode,
    map_order_intent_to_trade_request,
    select_mt5_filling_mode,
)
from acash.execution.mt5.normalizer import (
    DECIMAL_NORMALIZER_PRECISION,
    MT5SymbolNormalizer,
    convert_lots_to_units,
    convert_units_to_lots,
    normalize_price,
    normalize_volume,
    validate_boc_passivity,
    validate_stop_level,
)
from acash.execution.mt5.schemas import (
    BrokerSymbolSpec,
    MT5AccountReality,
    MT5DealReality,
    MT5ExecutionLineage,
    MT5OrderReality,
    MT5PositionReality,
    MT5TradeRequest,
    MT5TradeResult,
)
from acash.execution.mt5.transport import (
    MockMT5Transport,
    MT5HealthReport,
    MT5ReconciliationConfirmation,
    MT5TransportCommand,
    MT5TransportObservation,
    MT5TransportProtocol,
    MT5TransportSafetyState,
    NativeMT5Transport,
    TransportFailureCause,
)

__all__ = [
    # Enums
    "MT5AccountMarginMode",
    "MT5OrderType",
    "MT5FillingMode",
    "MT5ExecutionPolicy",
    "MT5TradeAction",
    "MT5OrderState",
    "MT5OrderTime",
    "MT5DealType",
    "MT5DealEntry",
    "MT5PositionType",
    "MT5TradeExecutionMode",
    "MT5Retcode",
    "MT5ApiErrorCode",
    # Exceptions
    "MT5DomainError",
    "MT5ValidationError",
    "MT5NormalizationError",
    "MT5RetcodeError",
    "MT5FillingModeError",
    "MT5SymbolSpecError",
    "MT5TransportError",
    "MT5ReconciliationError",
    "ReconciliationIntegrityError",
    # Schemas
    "BrokerSymbolSpec",
    "MT5TradeRequest",
    "MT5TradeResult",
    "MT5DealReality",
    "MT5OrderReality",
    "MT5PositionReality",
    "MT5AccountReality",
    "MT5ExecutionLineage",
    # Mapping
    "SUPPORTED_MT5_RETCODES",
    "REJECT_RETCODES",
    "MQL5_DEAL_TYPE_DECODE_MAP",
    "MQL5_DEAL_ENTRY_DECODE_MAP",
    "MQL5_MARGIN_MODE_DECODE_MAP",
    "decode_mt5_deal_type",
    "decode_mt5_deal_entry",
    "decode_mt5_margin_mode",
    "classify_trade_result_observation",
    "select_mt5_filling_mode",
    "map_order_intent_to_trade_request",
    # Normalizer & Sizing
    "DECIMAL_NORMALIZER_PRECISION",
    "MT5SymbolNormalizer",
    "normalize_volume",
    "normalize_price",
    "validate_stop_level",
    "validate_boc_passivity",
    "convert_units_to_lots",
    "convert_lots_to_units",
    # Transport & Adapter
    "TransportFailureCause",
    "MT5TransportSafetyState",
    "MT5HealthReport",
    "MT5TransportCommand",
    "MT5TransportObservation",
    "MT5ReconciliationConfirmation",
    "MT5TransportProtocol",
    "MockMT5Transport",
    "NativeMT5Transport",
    "MT5BrokerAdapter",
    "MT5BrokerObservation",
    # Reconciliation
    "MT5DiscrepancyKind",
    "MT5DiscrepancySeverity",
    "MT5Discrepancy",
    "ReconciliationToleranceConfig",
    "MT5DealCategory",
    "categorize_deal",
    "HistoricalDealScopeKind",
    "HistoricalDealCoverage",
    "CaptureCompletenessStatus",
    "ReconciliationCaptureContext",
    "ShadowPosition",
    "ShadowRestingOrder",
    "ShadowDealRecord",
    "ACASHShadowLedgerSnapshot",
    "ACASHShadowLedger",
    "MT5BrokerRealitySnapshot",
    "ReconciliationStatus",
    "MT56DReconciliationReport",
    "match_position_identity",
    "verify_order_deal_execution",
    "MT5ReconciliationEngine",
    "canonical_json",
    "compute_payload_digest",
]
