"""Canonical MQL5-aligned enumeration vocabulary for MetaTrader 5 execution."""

from enum import Enum


class MT5OrderType(str, Enum):
    """Canonical MT5 order types supported by MQL5 ENUM_ORDER_TYPE."""

    BUY = "BUY"
    SELL = "SELL"
    BUY_LIMIT = "BUY_LIMIT"
    SELL_LIMIT = "SELL_LIMIT"
    BUY_STOP = "BUY_STOP"
    SELL_STOP = "SELL_STOP"
    BUY_STOP_LIMIT = "BUY_STOP_LIMIT"
    SELL_STOP_LIMIT = "SELL_STOP_LIMIT"
    CLOSE_BY = "CLOSE_BY"  # Schema representation; generic mapping fails closed in Slice 1


class MT5FillingMode(str, Enum):
    """Canonical filling mode policies supported by MQL5 ENUM_ORDER_TYPE_FILLING."""

    ORDER_FILLING_FOK = "ORDER_FILLING_FOK"
    ORDER_FILLING_IOC = "ORDER_FILLING_IOC"
    ORDER_FILLING_RETURN = "ORDER_FILLING_RETURN"
    ORDER_FILLING_BOC = "ORDER_FILLING_BOC"


class MT5ExecutionPolicy(str, Enum):
    """ACASH sovereign intent execution policy."""

    DEFAULT = "DEFAULT"
    TAKER_SWEEP = "TAKER_SWEEP"
    PASSIVE_MAKER = "PASSIVE_MAKER"


class MT5TradeAction(str, Enum):
    """MQL5 trade request action types (ENUM_TRADE_REQUEST_ACTIONS)."""

    TRADE_ACTION_DEAL = "TRADE_ACTION_DEAL"
    TRADE_ACTION_PENDING = "TRADE_ACTION_PENDING"
    TRADE_ACTION_SLTP = "TRADE_ACTION_SLTP"
    TRADE_ACTION_MODIFY = "TRADE_ACTION_MODIFY"
    TRADE_ACTION_REMOVE = "TRADE_ACTION_REMOVE"
    TRADE_ACTION_CLOSE_BY = "TRADE_ACTION_CLOSE_BY"


class MT5OrderState(str, Enum):
    """MQL5 order state lifecycle representations (ENUM_ORDER_STATE)."""

    ORDER_STATE_STARTED = "ORDER_STATE_STARTED"
    ORDER_STATE_PLACED = "ORDER_STATE_PLACED"
    ORDER_STATE_CANCELED = "ORDER_STATE_CANCELED"
    ORDER_STATE_PARTIAL = "ORDER_STATE_PARTIAL"
    ORDER_STATE_FILLED = "ORDER_STATE_FILLED"
    ORDER_STATE_REJECTED = "ORDER_STATE_REJECTED"
    ORDER_STATE_EXPIRED = "ORDER_STATE_EXPIRED"
    ORDER_STATE_REQUEST_ADD = "ORDER_STATE_REQUEST_ADD"
    ORDER_STATE_REQUEST_MODIFY = "ORDER_STATE_REQUEST_MODIFY"
    ORDER_STATE_REQUEST_CANCEL = "ORDER_STATE_REQUEST_CANCEL"


class MT5OrderTime(str, Enum):
    """MQL5 order validity / expiration types (ENUM_ORDER_TYPE_TIME)."""

    ORDER_TIME_GTC = "ORDER_TIME_GTC"
    ORDER_TIME_DAY = "ORDER_TIME_DAY"
    ORDER_TIME_SPECIFIED = "ORDER_TIME_SPECIFIED"
    ORDER_TIME_SPECIFIED_DAY = "ORDER_TIME_SPECIFIED_DAY"


class MT5DealType(str, Enum):
    """MQL5 deal types (ENUM_DEAL_TYPE)."""

    DEAL_TYPE_BUY = "DEAL_TYPE_BUY"
    DEAL_TYPE_SELL = "DEAL_TYPE_SELL"
    DEAL_TYPE_BALANCE = "DEAL_TYPE_BALANCE"
    DEAL_TYPE_CREDIT = "DEAL_TYPE_CREDIT"
    DEAL_TYPE_CHARGE = "DEAL_TYPE_CHARGE"
    DEAL_TYPE_CORRECTION = "DEAL_TYPE_CORRECTION"
    DEAL_TYPE_BONUS = "DEAL_TYPE_BONUS"
    DEAL_TYPE_COMMISSION = "DEAL_TYPE_COMMISSION"
    DEAL_TYPE_COMMISSION_DAILY = "DEAL_TYPE_COMMISSION_DAILY"
    DEAL_TYPE_COMMISSION_MONTHLY = "DEAL_TYPE_COMMISSION_MONTHLY"
    DEAL_TYPE_COMMISSION_AGENT_DAILY = "DEAL_TYPE_COMMISSION_AGENT_DAILY"
    DEAL_TYPE_COMMISSION_AGENT_MONTHLY = "DEAL_TYPE_COMMISSION_AGENT_MONTHLY"
    DEAL_TYPE_INTEREST = "DEAL_TYPE_INTEREST"
    DEAL_TYPE_BUY_CANCELED = "DEAL_TYPE_BUY_CANCELED"
    DEAL_TYPE_SELL_CANCELED = "DEAL_TYPE_SELL_CANCELED"
    DEAL_DIVIDEND = "DEAL_DIVIDEND"
    DEAL_DIVIDEND_FRANKED = "DEAL_DIVIDEND_FRANKED"
    DEAL_TAX = "DEAL_TAX"


class MT5DealEntry(str, Enum):
    """MQL5 deal direction / entry types (ENUM_DEAL_ENTRY)."""

    DEAL_ENTRY_IN = "DEAL_ENTRY_IN"
    DEAL_ENTRY_OUT = "DEAL_ENTRY_OUT"
    DEAL_ENTRY_INOUT = "DEAL_ENTRY_INOUT"
    DEAL_ENTRY_OUT_BY = "DEAL_ENTRY_OUT_BY"


class MT5PositionType(str, Enum):
    """MQL5 position types (ENUM_POSITION_TYPE)."""

    POSITION_TYPE_BUY = "POSITION_TYPE_BUY"
    POSITION_TYPE_SELL = "POSITION_TYPE_SELL"


class MT5TradeExecutionMode(str, Enum):
    """MQL5 symbol trade execution modes (ENUM_SYMBOL_TRADE_EXECUTION)."""

    SYMBOL_TRADE_EXECUTION_REQUEST = "SYMBOL_TRADE_EXECUTION_REQUEST"
    SYMBOL_TRADE_EXECUTION_INSTANT = "SYMBOL_TRADE_EXECUTION_INSTANT"
    SYMBOL_TRADE_EXECUTION_MARKET = "SYMBOL_TRADE_EXECUTION_MARKET"
    SYMBOL_TRADE_EXECUTION_EXCHANGE = "SYMBOL_TRADE_EXECUTION_EXCHANGE"


class MT5Retcode(int, Enum):
    """MQL5 trade server return codes (ENUM_TRADE_RETCODE)."""

    TRADE_RETCODE_REQUOTE = 10004
    TRADE_RETCODE_REJECT = 10006
    TRADE_RETCODE_CANCEL = 10007
    TRADE_RETCODE_PLACED = 10008
    TRADE_RETCODE_DONE = 10009
    TRADE_RETCODE_DONE_PARTIAL = 10010
    TRADE_RETCODE_ERROR = 10011
    TRADE_RETCODE_TIMEOUT = 10012
    TRADE_RETCODE_INVALID = 10013
    TRADE_RETCODE_INVALID_VOLUME = 10014
    TRADE_RETCODE_INVALID_PRICE = 10015
    TRADE_RETCODE_INVALID_STOPS = 10016
    TRADE_RETCODE_TRADE_DISABLED = 10017
    TRADE_RETCODE_MARKET_CLOSED = 10018
    TRADE_RETCODE_NO_MONEY = 10019
    TRADE_RETCODE_PRICE_CHANGED = 10020
    TRADE_RETCODE_PRICE_OFF = 10021
    TRADE_RETCODE_INVALID_EXPIRATION = 10022
    TRADE_RETCODE_ORDER_CHANGED = 10023
    TRADE_RETCODE_TOO_MANY_REQUESTS = 10024
    TRADE_RETCODE_NO_CHANGES = 10025
    TRADE_RETCODE_SERVER_DISABLES_AT = 10026
    TRADE_RETCODE_CLIENT_DISABLES_AT = 10027
    TRADE_RETCODE_LOCKED = 10028
    TRADE_RETCODE_FROZEN = 10029
    TRADE_RETCODE_INVALID_FILL = 10030
    TRADE_RETCODE_CONNECTION = 10031
    TRADE_RETCODE_ONLY_REAL = 10032
    TRADE_RETCODE_LIMIT_ORDERS = 10033
    TRADE_RETCODE_LIMIT_VOLUME = 10034
    TRADE_RETCODE_INVALID_ORDER = 10035
    TRADE_RETCODE_POSITION_CLOSED = 10036
    TRADE_RETCODE_INVALID_CLOSE_VOLUME = 10038
    TRADE_RETCODE_CLOSE_ORDER_EXIST = 10039
    TRADE_RETCODE_LIMIT_POSITIONS = 10040
    TRADE_RETCODE_REJECT_CANCEL = 10041
    TRADE_RETCODE_LONG_ONLY = 10042
    TRADE_RETCODE_SHORT_ONLY = 10043
    TRADE_RETCODE_CLOSE_ONLY = 10044
    TRADE_RETCODE_FIFO_CLOSE = 10045
    TRADE_RETCODE_HEDGE_PROHIBITED = 10046


class MT5ApiErrorCode(int, Enum):
    """MetaTrader 5 Python client library return codes from mt5.last_error().

    Strictly separate from trade server retcodes (MT5Retcode / ENUM_TRADE_RETCODE).
    """

    RES_S_OK = 1
    RES_E_FAIL = -1
    RES_E_INVALID_PARAMS = -2
    RES_E_NO_MEMORY = -3
    RES_E_NOT_FOUND = -4
    RES_E_INVALID_VERSION = -5
    RES_E_AUTH_FAILED = -6
    RES_E_UNSUPPORTED = -7
    RES_E_AUTO_TRADING_DISABLED = -8
    RES_E_INTERNAL_FAIL = -10000
    RES_E_INTERNAL_FAIL_SEND = -10001
    RES_E_INTERNAL_FAIL_RECEIVE = -10002
    RES_E_INTERNAL_FAIL_INIT = -10003
    RES_E_INTERNAL_FAIL_CONNECT = -10004
    RES_E_INTERNAL_FAIL_TIMEOUT = -10005

