"""Per-stream data integrity validator and anomaly engine for the ACASH market data subsystem.

Strictly separates:
- FATAL ERRORS (Rejects batch / invalidates dataset)
- ANOMALIES / WARNINGS (Preserves observation & flags for research)

Enforces:
- Distinct event-time monotonicity
- event_end_utc consistency across revisions
- Event-scoped immutable revision_seq uniqueness
- Intra-batch same-knowledge fingerprint tie-breaker
- Duplicate revision content rejection
- Configurable session profiles
"""

from dataclasses import dataclass, field
from datetime import datetime, timezone, timedelta
from decimal import Decimal
from enum import Enum
from typing import Any, Dict, List, Optional, Sequence, Tuple
import pyarrow as pa

from acash.data.provenance import calculate_canonical_content_fingerprint
from acash.data.schema import (
    DomainValidationError,
    validate_decimal128_bounds,
)


class SessionProfile(str, Enum):
    """Trading session calendars for cadence and gap validation."""
    CRYPTO_24_7 = "CRYPTO_24_7"
    FX_24_5_DEFAULT = "FX_24_5_DEFAULT"
    EQUITY_SESSION_DEFAULT = "EQUITY_SESSION_DEFAULT"
    CUSTOM = "CUSTOM"


@dataclass(frozen=True)
class ValidationErrorRecord:
    """Represents a fatal integrity rule violation."""
    rule: str
    message: str
    stream_key: str
    row_index: Optional[int] = None
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ValidationAnomalyRecord:
    """Represents a statistical or market anomaly preserved without altering data."""
    rule: str
    message: str
    stream_key: str
    row_index: Optional[int] = None
    details: Dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True)
class ValidationMetrics:
    """Summary metrics of the validated dataset."""
    total_rows: int
    stream_count: int
    min_event_time_utc: Optional[datetime] = None
    max_event_time_utc: Optional[datetime] = None
    min_price: Optional[Decimal] = None
    max_price: Optional[Decimal] = None
    total_volume: Optional[Decimal] = None


@dataclass
class ValidationReport:
    """Complete report generated by the DataIntegrityValidator."""
    is_valid: bool
    errors: List[ValidationErrorRecord] = field(default_factory=list)
    warnings: List[ValidationAnomalyRecord] = field(default_factory=list)
    metrics: Optional[ValidationMetrics] = None

    @property
    def error_count(self) -> int:
        return len(self.errors)

    @property
    def warning_count(self) -> int:
        return len(self.warnings)


class DataIntegrityValidator:
    """Per-stream data integrity validator for ACASH market data."""

    def __init__(
        self,
        session_profile: SessionProfile = SessionProfile.CRYPTO_24_7,
        price_jump_threshold_pct: Decimal = Decimal("0.20"),  # 20% jump warning
        volume_spike_multiplier: Decimal = Decimal("10.0"),  # 10x median volume
    ) -> None:
        self.session_profile = session_profile
        self.price_jump_threshold_pct = price_jump_threshold_pct
        self.volume_spike_multiplier = volume_spike_multiplier

    def validate_table(
        self,
        table: pa.Table,
        existing_revisions_lookup: Optional[Dict[Tuple[str, str, str, datetime, datetime, int], bool]] = None,
    ) -> Tuple[ValidationReport, pa.Table]:
        """Validate a PyArrow table per stream and deterministically assign revision_seq if needed.

        Returns:
            (ValidationReport, normalized_and_sequenced_pa_table)
        """
        errors: List[ValidationErrorRecord] = []
        warnings: List[ValidationAnomalyRecord] = []

        if table.num_rows == 0:
            report = ValidationReport(
                is_valid=True,
                errors=[],
                warnings=[],
                metrics=ValidationMetrics(total_rows=0, stream_count=0),
            )
            return report, table

        # Convert table to records for per-stream processing
        rows = table.to_pylist()

        # Group rows by independent stream: (source_id, symbol, timeframe)
        streams: Dict[Tuple[str, str, str], List[Tuple[int, Dict[str, Any]]]] = {}
        for idx, row in enumerate(rows):
            stream_key = (str(row["source_id"]), str(row["symbol"]), str(row["timeframe"]))
            if stream_key not in streams:
                streams[stream_key] = []
            streams[stream_key].append((idx, row))

        min_event_time: Optional[datetime] = None
        max_event_time: Optional[datetime] = None
        min_price: Optional[Decimal] = None
        max_price: Optional[Decimal] = None
        total_volume: Decimal = Decimal("0")

        processed_rows: List[Dict[str, Any]] = []

        # Process each stream independently
        for stream_key, stream_items in streams.items():
            stream_str = f"{stream_key[0]}:{stream_key[1]}:{stream_key[2]}"
            stream_errors, stream_warnings, sequenced_stream_rows = self._validate_and_sequence_stream(
                stream_key=stream_key,
                stream_items=stream_items,
                existing_revisions_lookup=existing_revisions_lookup,
            )
            errors.extend(stream_errors)
            warnings.extend(stream_warnings)
            processed_rows.extend(sequenced_stream_rows)

            for r in sequenced_stream_rows:
                estart = r["event_start_utc"]
                if isinstance(estart, datetime):
                    if min_event_time is None or estart < min_event_time:
                        min_event_time = estart
                    if max_event_time is None or estart > max_event_time:
                        max_event_time = estart

                close_p = Decimal(str(r["close"]))
                if min_price is None or close_p < min_price:
                    min_price = close_p
                if max_price is None or close_p > max_price:
                    max_price = close_p

                vol = Decimal(str(r["volume"]))
                total_volume += vol

        is_valid = len(errors) == 0

        # Build reconstructed table matching canonical schema
        if is_valid and processed_rows:
            # Sort all rows by Revision Identity
            processed_rows.sort(key=lambda r: (
                r["source_id"],
                r["symbol"],
                r["timeframe"],
                r["event_start_utc"],
                r["knowledge_time_utc"],
                r["revision_seq"],
            ))
            # Build PyArrow table
            out_dict: Dict[str, list[Any]] = {
                "source_id": [r["source_id"] for r in processed_rows],
                "symbol": [r["symbol"] for r in processed_rows],
                "timeframe": [r["timeframe"] for r in processed_rows],
                "event_start_utc": [r["event_start_utc"] for r in processed_rows],
                "event_end_utc": [r["event_end_utc"] for r in processed_rows],
                "knowledge_time_utc": [r["knowledge_time_utc"] for r in processed_rows],
                "revision_seq": [r["revision_seq"] for r in processed_rows],
                "open": [r["open"] for r in processed_rows],
                "high": [r["high"] for r in processed_rows],
                "low": [r["low"] for r in processed_rows],
                "close": [r["close"] for r in processed_rows],
                "volume": [r["volume"] for r in processed_rows],
                "quote_volume": [r["quote_volume"] for r in processed_rows],
                "trade_count": [r["trade_count"] for r in processed_rows],
            }
            from acash.data.schema import CANONICAL_ARROW_SCHEMA
            out_table = pa.Table.from_pydict(out_dict, schema=CANONICAL_ARROW_SCHEMA)
        else:
            out_table = table

        metrics = ValidationMetrics(
            total_rows=len(rows),
            stream_count=len(streams),
            min_event_time_utc=min_event_time,
            max_event_time_utc=max_event_time,
            min_price=min_price,
            max_price=max_price,
            total_volume=total_volume,
        )

        report = ValidationReport(
            is_valid=is_valid,
            errors=errors,
            warnings=warnings,
            metrics=metrics,
        )
        return report, out_table

    def _validate_and_sequence_stream(
        self,
        stream_key: Tuple[str, str, str],
        stream_items: List[Tuple[int, Dict[str, Any]]],
        existing_revisions_lookup: Optional[Dict[Tuple[str, str, str, datetime, datetime, int], bool]] = None,
    ) -> Tuple[List[ValidationErrorRecord], List[ValidationAnomalyRecord], List[Dict[str, Any]]]:
        """Validate an individual stream and assign deterministic revision sequences."""
        errors: List[ValidationErrorRecord] = []
        warnings: List[ValidationAnomalyRecord] = []
        stream_str = f"{stream_key[0]}:{stream_key[1]}:{stream_key[2]}"

        # Step 1: Validate individual row boundaries, finite decimals, positive prices, etc.
        validated_stream_rows: List[Dict[str, Any]] = []
        for orig_idx, row in stream_items:
            row_dict = dict(row)
            try:
                # Value Validation & Normalization
                open_p = Decimal(str(row_dict["open"]))
                high_p = Decimal(str(row_dict["high"]))
                low_p = Decimal(str(row_dict["low"]))
                close_p = Decimal(str(row_dict["close"]))
                vol = Decimal(str(row_dict["volume"]))
                quote_vol = Decimal(str(row_dict["quote_volume"]))
                trade_count = int(row_dict["trade_count"])

                for name, dec_val in [
                    ("open", open_p), ("high", high_p), ("low", low_p),
                    ("close", close_p), ("volume", vol), ("quote_volume", quote_vol)
                ]:
                    validate_decimal128_bounds(dec_val, name)

                # Price positivity
                if open_p <= Decimal("0") or high_p <= Decimal("0") or low_p <= Decimal("0") or close_p <= Decimal("0"):
                    errors.append(ValidationErrorRecord(
                        rule="POSITIVE_PRICE",
                        message=f"Prices must be strictly positive (> 0): O={open_p}, H={high_p}, L={low_p}, C={close_p}",
                        stream_key=stream_str,
                        row_index=orig_idx,
                    ))

                # Volume non-negativity
                if vol < Decimal("0") or quote_vol < Decimal("0"):
                    errors.append(ValidationErrorRecord(
                        rule="NON_NEGATIVE_VOLUME",
                        message=f"Volume must be non-negative: volume={vol}, quote_volume={quote_vol}",
                        stream_key=stream_str,
                        row_index=orig_idx,
                    ))

                # OHLC Geometry
                max_oc = max(open_p, close_p)
                min_oc = min(open_p, close_p)
                if high_p < max_oc:
                    errors.append(ValidationErrorRecord(
                        rule="OHLC_GEOMETRY_HIGH",
                        message=f"High ({high_p}) must be >= max(open, close) ({max_oc})",
                        stream_key=stream_str,
                        row_index=orig_idx,
                    ))
                if low_p > min_oc:
                    errors.append(ValidationErrorRecord(
                        rule="OHLC_GEOMETRY_LOW",
                        message=f"Low ({low_p}) must be <= min(open, close) ({min_oc})",
                        stream_key=stream_str,
                        row_index=orig_idx,
                    ))
                if high_p < low_p:
                    errors.append(ValidationErrorRecord(
                        rule="OHLC_GEOMETRY_SPAN",
                        message=f"High ({high_p}) cannot be less than Low ({low_p})",
                        stream_key=stream_str,
                        row_index=orig_idx,
                    ))

                # Timestamp Normalization & Invariants
                estart = row_dict["event_start_utc"]
                eend = row_dict["event_end_utc"]
                know = row_dict["knowledge_time_utc"]

                def ensure_utc(ts: Any, field_name: str) -> datetime:
                    if not isinstance(ts, datetime):
                        raise DomainValidationError(f"{field_name} must be a datetime, got {type(ts)}")
                    if ts.tzinfo is None:
                        raise DomainValidationError(f"{field_name} must be timezone-aware UTC datetime")
                    return ts.astimezone(timezone.utc)

                estart = ensure_utc(estart, "event_start_utc")
                eend = ensure_utc(eend, "event_end_utc")
                know = ensure_utc(know, "knowledge_time_utc")

                if estart >= eend:
                    errors.append(ValidationErrorRecord(
                        rule="INTRA_BAR_INTERVAL",
                        message=f"event_start_utc ({estart}) must precede event_end_utc ({eend})",
                        stream_key=stream_str,
                        row_index=orig_idx,
                    ))
                if know < eend:
                    errors.append(ValidationErrorRecord(
                        rule="KNOWLEDGE_INVARIANT",
                        message=f"Lookahead detected: knowledge_time_utc ({know}) cannot precede event_end_utc ({eend})",
                        stream_key=stream_str,
                        row_index=orig_idx,
                    ))

                row_dict["open"] = open_p
                row_dict["high"] = high_p
                row_dict["low"] = low_p
                row_dict["close"] = close_p
                row_dict["volume"] = vol
                row_dict["quote_volume"] = quote_vol
                row_dict["trade_count"] = trade_count
                row_dict["event_start_utc"] = estart
                row_dict["event_end_utc"] = eend
                row_dict["knowledge_time_utc"] = know
                row_dict["_orig_idx"] = orig_idx

                validated_stream_rows.append(row_dict)

            except Exception as ex:
                errors.append(ValidationErrorRecord(
                    rule="SCHEMA_CONFORMANCE",
                    message=f"Row failed schema validation: {ex}",
                    stream_key=stream_str,
                    row_index=orig_idx,
                ))

        if errors:
            return errors, warnings, validated_stream_rows

        # Step 2: Group by Event Observation: event_start_utc
        # Invariant: event_end_utc MUST be consistent across all revisions sharing event_start_utc
        event_groups: Dict[datetime, List[Dict[str, Any]]] = {}
        for r in validated_stream_rows:
            estart = r["event_start_utc"]
            if estart not in event_groups:
                event_groups[estart] = []
            event_groups[estart].append(r)

        # Validate event_end consistency across revisions for each event
        for estart, group in event_groups.items():
            first_eend = group[0]["event_end_utc"]
            for r in group[1:]:
                if r["event_end_utc"] != first_eend:
                    errors.append(ValidationErrorRecord(
                        rule="EVENT_END_CONSISTENCY",
                        message=(
                            f"Inconsistent event_end_utc for Event ({estart}): "
                            f"first revision had {first_eend}, but revision had {r['event_end_utc']}"
                        ),
                        stream_key=stream_str,
                        row_index=r.get("_orig_idx"),
                    ))

        # Step 3: Validate Distinct Event Monotonicity
        distinct_event_starts = sorted(event_groups.keys())
        for i in range(len(distinct_event_starts) - 1):
            curr_start = distinct_event_starts[i]
            next_start = distinct_event_starts[i + 1]
            curr_end = event_groups[curr_start][0]["event_end_utc"]
            if next_start < curr_end:
                errors.append(ValidationErrorRecord(
                    rule="DISTINCT_EVENT_MONOTONICITY",
                    message=(
                        f"Distinct event overlap/monotonicity violation: Event {curr_start} closes at {curr_end}, "
                        f"but next event begins at {next_start}"
                    ),
                    stream_key=stream_str,
                ))

        # Step 4: Handle revision_seq uniqueness & deterministic assignment
        sequenced_stream_rows: List[Dict[str, Any]] = []
        for estart in distinct_event_starts:
            group = event_groups[estart]

            # Check if source provided revision_seq
            has_source_seq = all(
                r.get("revision_seq") is not None and int(r.get("revision_seq", 0)) >= 1
                for r in group
            )

            if has_source_seq:
                # Validate source sequence uniqueness within event
                seen_seqs: set[int] = set()
                for r in group:
                    seq_val = int(r["revision_seq"])
                    if seq_val in seen_seqs:
                        errors.append(ValidationErrorRecord(
                            rule="DUPLICATE_REVISION_SEQ",
                            message=f"Duplicate revision_seq {seq_val} found within Event Observation ({estart})",
                            stream_key=stream_str,
                            row_index=r.get("_orig_idx"),
                        ))
                    seen_seqs.add(seq_val)
                    r["revision_seq"] = seq_val
                    sequenced_stream_rows.append(r)
            else:
                # ACASH assigns revision_seq deterministically upon first acceptance
                # Compute fingerprint for each revision in group
                for r in group:
                    r["_fingerprint"] = calculate_canonical_content_fingerprint(
                        open_price=r["open"],
                        high_price=r["high"],
                        low_price=r["low"],
                        close_price=r["close"],
                        volume=r["volume"],
                        quote_volume=r["quote_volume"],
                        trade_count=r["trade_count"],
                    )

                # Check duplicate content at same knowledge time
                seen_knowledge_content: set[Tuple[datetime, str]] = set()
                for r in group:
                    kc_key = (r["knowledge_time_utc"], r["_fingerprint"])
                    if kc_key in seen_knowledge_content:
                        errors.append(ValidationErrorRecord(
                            rule="DUPLICATE_REVISION_CONTENT",
                            message=(
                                f"Duplicate revision content detected for Event ({estart}) "
                                f"at knowledge_time {r['knowledge_time_utc']}"
                            ),
                            stream_key=stream_str,
                            row_index=r.get("_orig_idx"),
                        ))
                    seen_knowledge_content.add(kc_key)

                # Deterministic sorting for unpersisted revisions: knowledge_time_utc ASC -> canonical_content_fingerprint ASC
                group.sort(key=lambda r: (r["knowledge_time_utc"], r["_fingerprint"]))
                for seq_idx, r in enumerate(group, start=1):
                    r["revision_seq"] = seq_idx
                    r.pop("_fingerprint", None)
                    sequenced_stream_rows.append(r)

        # Step 5: Validate global Revision Identity uniqueness against existing dataset
        if existing_revisions_lookup is not None:
            for r in sequenced_stream_rows:
                rev_id = (
                    r["source_id"],
                    r["symbol"],
                    r["timeframe"],
                    r["event_start_utc"],
                    r["knowledge_time_utc"],
                    r["revision_seq"],
                )
                if rev_id in existing_revisions_lookup:
                    errors.append(ValidationErrorRecord(
                        rule="GLOBAL_REVISION_IDENTITY_DUPLICATE",
                        message=f"Revision Identity {rev_id} already exists in canonical dataset",
                        stream_key=stream_str,
                        row_index=r.get("_orig_idx"),
                    ))

        # Step 6: Anomaly Checks (Warnings without modifying data)
        # Price spikes and volume anomalies
        for i in range(len(sequenced_stream_rows) - 1):
            curr_r = sequenced_stream_rows[i]
            next_r = sequenced_stream_rows[i + 1]
            if curr_r["event_start_utc"] != next_r["event_start_utc"]:
                p1 = curr_r["close"]
                p2 = next_r["close"]
                ret = abs(p2 - p1) / p1
                if ret > self.price_jump_threshold_pct:
                    warnings.append(ValidationAnomalyRecord(
                        rule="PRICE_RETURN_SPIKE",
                        message=f"Large price return jump: {ret:.2%} between {curr_r['event_start_utc']} and {next_r['event_start_utc']}",
                        stream_key=stream_str,
                        details={"return": str(ret), "prev_close": str(p1), "next_close": str(p2)},
                    ))

        # Clean internal metadata
        for r in sequenced_stream_rows:
            r.pop("_orig_idx", None)

        return errors, warnings, sequenced_stream_rows
